# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fd1206f1-f275-4035-b74b-26e79a50193f";
    fsType = "ext4";
  };

  fileSystems."/booty" = {
    device = "/dev/disk/by-uuid/396a47fe-d18a-4f86-b4ea-f4a62d5dd113";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/a99f5fe3-565c-420b-824f-e65e8f4ee736"; }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
