# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "virtio_pci" "virtio_scsi" "usbhid" ];
  boot.initrd.kernelModules = [ "nvme" ];
  boot.loader.grub = {
    efiSupport = true;
    efiInstallAsRemovable = true;
    device = "nodev";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/098aab8a-579b-4376-b268-fba317eab5d1";
    fsType = "btrfs";
    options = [ "compress=zstd" "space_cache=v2" ];
  };
  fileSystems."/sync" = {
    device = "/dev/disk/by-uuid/098aab8a-579b-4376-b268-fba317eab5d1";
    fsType = "btrfs";
    options = [ "compress-force=zstd:15" "noatime" "space_cache=v2" "subvol=sync" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D57C-6430";
    fsType = "vfat";
  };

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
